export type ArchetypeCardCopy = {
  displayName: string
  headline: string
}

export const femaleArchetypeCardCopy: Record<string, ArchetypeCardCopy> = {
  root_sacral: { displayName: '日子盘串人', headline: '把生活揉成包浆，连冰箱贴都很有秩序。' },
  root_solar: { displayName: '稳住哥', headline: '别人慌成弹幕，你已经开始排流程。' },
  root_heart: { displayName: '人形安全屋', headline: '你一出现，大家自动把心放回肚子里。' },
  root_throat: { displayName: '靠谱传话筒', headline: '同一句话，经你转述突然就能落地。' },
  root_thirdEye: { displayName: '落地军师', headline: '脑子在天上飞，脚却稳稳踩在地砖上。' },
  root_crown: { displayName: '人间修行搭子', headline: '一边悟道，一边记得交水电费。' },
  sacral_root: { displayName: '会过日子精', headline: '你不是生活，你是在给日常加滤镜。' },
  sacral_solar: { displayName: '上头行动派', headline: '灵感刚冒泡，你人已经冲出门了。' },
  sacral_heart: { displayName: '情绪补给站', headline: '朋友电量低时，会自动来你这里充电。' },
  sacral_throat: { displayName: '灵感喷泉', headline: '你一开口，脑洞就开始冒泡泡。' },
  sacral_thirdEye: { displayName: '脑洞造梦机', headline: '你脑内小剧场常年续订第二季。' },
  sacral_crown: { displayName: '宇宙调色盘', headline: '你把灵感蘸一蘸，就能涂出另一个世界。' },
  solar_root: { displayName: '死磕执行官', headline: '目标一旦锁定，你连拖延症都能拖走。' },
  solar_sacral: { displayName: '热血打火机', headline: '你负责点燃现场，顺便把大家也点亮。' },
  solar_heart: { displayName: '老好人', headline: '嘴上说都行，手里已经把全场安排好了。' },
  solar_throat: { displayName: '气氛带货王', headline: '你不是讲话，你是在给全场加 buff。' },
  solar_thirdEye: { displayName: '棋盘掌控者', headline: '你看似在发呆，其实已经推演三局。' },
  solar_crown: { displayName: '理想施工队', headline: '别人谈理想，你已经拿着图纸开工。' },
  heart_root: { displayName: '抱抱基地', headline: '你像一个可移动的安全毯。' },
  heart_sacral: { displayName: '情绪暖宝宝', headline: '你一靠近，关系里的冰块就开始融化。' },
  heart_solar: { displayName: '老好人', headline: '你不是没脾气，你是会把场面照顾好。' },
  heart_throat: { displayName: '嘴替棉花糖', headline: '你能把难听的话说到别人愿意听。' },
  heart_thirdEye: { displayName: '显微镜疗愈师', headline: '你不是看穿别人，是看见没说出口的委屈。' },
  heart_crown: { displayName: '宇宙慈善家', headline: '你爱一个人，也顺手想抱抱全世界。' },
  throat_root: { displayName: '实话落地机', headline: '你说真话，但会给真话装个降落伞。' },
  throat_sacral: { displayName: '表达上头人', headline: '一有感觉，你的嘴和手就同步上线。' },
  throat_solar: { displayName: '开麦控场王', headline: '麦一到手，场子就有了方向。' },
  throat_heart: { displayName: '共情翻译官', headline: '你负责把心里话翻译成人话。' },
  throat_thirdEye: { displayName: '复杂说明书', headline: '你能把一团乱麻讲成三步走。' },
  throat_crown: { displayName: '玄学翻译器', headline: '高维道理经你一讲，突然接地气了。' },
  thirdEye_root: { displayName: '现实雷达员', headline: '别人看热闹，你已经看见底层结构。' },
  thirdEye_sacral: { displayName: '脑内导演', headline: '你脑子里常驻一个片场，预算还很高。' },
  thirdEye_solar: { displayName: '预判大师', headline: '你还没出手，已经看到对面下一步。' },
  thirdEye_heart: { displayName: '读心售后', headline: '你看穿了，但通常还会递一张纸巾。' },
  thirdEye_throat: { displayName: '人间说明书', headline: '复杂世界到你嘴里，突然有目录了。' },
  thirdEye_crown: { displayName: '边缘OB人', headline: '你站在局外看得很清，偶尔还会补一句。' },
  crown_root: { displayName: '落地仙人', headline: '你不是飘，你只是把灵感插了地线。' },
  crown_sacral: { displayName: '灵感接收器', headline: '像天线上身，随时接到奇妙信号。' },
  crown_solar: { displayName: '使命卷王', headline: '你不是想赢，你是觉得这事必须成。' },
  crown_heart: { displayName: '大爱发电站', headline: '你用爱发电，而且电压还挺稳。' },
  crown_throat: { displayName: '智慧广播站', headline: '你负责把云端内容广播到人间。' },
  crown_thirdEye: { displayName: '边缘OB人', headline: '你不入局，但你的弹幕经常很准。' }
}
